# Generated by Django 2.1.3 on 2018-11-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogirl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangogirl',
            name='website_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
